-- Daily Missions V1: one stable, persisted study plan per learner/track/day.
--
-- A Daily Mission is a SNAPSHOT. It is generated once for the day and never
-- regenerated by completing items, state changes, refreshes, or repeated
-- requests. Progress and the completion reward are server-authoritative.
--
-- The day boundary is a single canonical UTC day (`day_key`). The client IANA
-- timezone is stored as metadata only and does not affect scoping, so changing
-- the timezone cannot create a second reward-bearing mission for the same day.

CREATE TABLE daily_missions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    track_id text NOT NULL,
    track_version text NOT NULL,
    day_key date NOT NULL,
    timezone text,
    plan_type text NOT NULL,
    status text NOT NULL DEFAULT 'active',
    reward_bits integer NOT NULL,
    reward_settled_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    CONSTRAINT daily_missions_plan_type_valid CHECK (plan_type IN ('adaptive', 'standard')),
    CONSTRAINT daily_missions_status_valid CHECK (status IN ('active', 'completed')),
    CONSTRAINT daily_missions_reward_non_negative CHECK (reward_bits >= 0),
    CONSTRAINT daily_missions_track_not_blank CHECK (btrim(track_id) <> ''),
    CONSTRAINT daily_missions_version_not_blank CHECK (btrim(track_version) <> ''),
    -- One mission per learner, track, and canonical day.
    CONSTRAINT daily_missions_user_track_day_unique UNIQUE (user_id, track_id, day_key)
);

-- Query pattern: a learner's recent daily missions.
CREATE INDEX daily_missions_user_created_idx ON daily_missions (user_id, created_at);

CREATE TABLE daily_mission_items (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    daily_mission_id uuid NOT NULL REFERENCES daily_missions (id) ON DELETE CASCADE,
    position integer NOT NULL,
    kind text NOT NULL,
    domain_id text NOT NULL,
    node_id text,
    title text NOT NULL,
    estimated_minutes integer NOT NULL DEFAULT 0,
    practice_context jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'pending',
    completed_at timestamptz,
    CONSTRAINT daily_mission_items_kind_valid CHECK (
        kind IN ('learn_node', 'review_node', 'practice', 'domain_practice')
    ),
    CONSTRAINT daily_mission_items_status_valid CHECK (status IN ('pending', 'completed')),
    CONSTRAINT daily_mission_items_position_non_negative CHECK (position >= 0),
    CONSTRAINT daily_mission_items_estimated_non_negative CHECK (estimated_minutes >= 0),
    CONSTRAINT daily_mission_items_context_object CHECK (jsonb_typeof(practice_context) = 'object'),
    CONSTRAINT daily_mission_items_unique_position UNIQUE (daily_mission_id, position)
);

-- Query pattern: load one mission's ordered items.
CREATE INDEX daily_mission_items_mission_idx
    ON daily_mission_items (daily_mission_id, position);

-- Link a scored mission back to the Daily Mission item it executes. Context
-- only, never an authorization or ownership key.
ALTER TABLE mission_instances
    ADD COLUMN daily_mission_id uuid,
    ADD COLUMN daily_item_position integer;

-- Query pattern: find the mission(s) started for one daily item.
CREATE INDEX mission_instances_daily_item_idx
    ON mission_instances (daily_mission_id, daily_item_position)
    WHERE daily_mission_id IS NOT NULL;
