//! Best-effort auxiliary recommendation history and lifecycle telemetry.
//!
//! This is not learning evidence. It exists only so recommendation quality can be
//! evaluated later, and every write is optional: callers ignore failures so a
//! logging or telemetry problem can never block a recommendation, a mission, or
//! a learning event. These writes never share a transaction with authoritative
//! learning-event persistence.

use sqlx::PgPool;
use uuid::Uuid;

use crate::DbError;

/// One recommendation generated for a learner.
#[derive(Debug, Clone, PartialEq)]
pub struct RecommendationLogEntry<'a> {
    /// Stable recommendation id returned to the client and used by lifecycle
    /// events. Generated by the caller before the response is built.
    pub recommendation_id: Uuid,
    /// Owning learner.
    pub user_id: Uuid,
    /// Learning track identifier.
    pub track_id: &'a str,
    /// Learning track version identifier.
    pub track_version: &'a str,
    /// Chosen action, for example `learn_node`.
    pub action: &'a str,
    /// Stable reason code, for example `weak_concept`.
    pub reason: &'a str,
    /// Domain/topic the action belongs to.
    pub domain_id: Option<&'a str>,
    /// Knowledge node, when node-based.
    pub node_id: Option<&'a str>,
    /// Question, when question-based.
    pub question_id: Option<&'a str>,
    /// Concepts the recommendation targets.
    pub concept_ids: &'a [String],
}

/// One lifecycle event for a recommendation.
#[derive(Debug, Clone, PartialEq)]
pub struct RecommendationEventEntry<'a> {
    /// Stable client-generated id, used to make retried telemetry idempotent.
    pub event_id: Uuid,
    /// Recommendation the event refers to.
    pub recommendation_id: Uuid,
    /// Owning learner.
    pub user_id: Uuid,
    /// Learning track identifier.
    pub track_id: &'a str,
    /// Lifecycle stage: `generated`, `shown`, `clicked`, `started`,
    /// `node_opened`, or `completed`.
    pub event: &'a str,
    /// Planner action, when known.
    pub action: Option<&'a str>,
    /// Domain/topic, when known.
    pub domain_id: Option<&'a str>,
    /// Knowledge node, when known.
    pub node_id: Option<&'a str>,
    /// Question, when known.
    pub question_id: Option<&'a str>,
}

/// Appends one generated recommendation record.
///
/// Callers must treat this as best-effort and ignore errors.
pub async fn log(pool: &PgPool, entry: &RecommendationLogEntry<'_>) -> Result<(), DbError> {
    sqlx::query(
        "INSERT INTO recommendation_log
            (recommendation_id, user_id, track_id, track_version, action, reason, domain_id, node_id,
             question_id, concept_ids)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)",
    )
    .bind(entry.recommendation_id)
    .bind(entry.user_id)
    .bind(entry.track_id)
    .bind(entry.track_version)
    .bind(entry.action)
    .bind(entry.reason)
    .bind(entry.domain_id)
    .bind(entry.node_id)
    .bind(entry.question_id)
    .bind(entry.concept_ids)
    .execute(pool)
    .await?;

    Ok(())
}

/// Appends one recommendation lifecycle event.
///
/// Idempotent by `event_id`: a retried batch cannot insert the same event twice.
/// Callers must treat this as best-effort and ignore errors.
pub async fn record_event(
    pool: &PgPool,
    entry: &RecommendationEventEntry<'_>,
) -> Result<(), DbError> {
    sqlx::query(
        "INSERT INTO recommendation_events
            (event_id, recommendation_id, user_id, track_id, event, action, domain_id, node_id,
             question_id)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
         ON CONFLICT (event_id) DO NOTHING",
    )
    .bind(entry.event_id)
    .bind(entry.recommendation_id)
    .bind(entry.user_id)
    .bind(entry.track_id)
    .bind(entry.event)
    .bind(entry.action)
    .bind(entry.domain_id)
    .bind(entry.node_id)
    .bind(entry.question_id)
    .execute(pool)
    .await?;

    Ok(())
}
