/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness and dependency check.
         * @description Returns `200` when the database is reachable and `503` when it is not, so a
         *     load balancer can stop routing to an instance whose dependency is down.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serves the generated OpenAPI document.
         * @description The document is the source of truth for the TypeScript client. Regenerate it
         *     with `cargo run -p adaptive-learn-api --bin export-openapi` or the web
         *     `pnpm generate:api` script.
         */
        get: operations["openapi_json"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/certifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists certifications, versions, domains, and authored tasks. */
        get: operations["list_certifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/certifications/{certification_id}/domains/{domain_id}/learning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns the pre-quiz learning content for a certification domain.
         * @description This is the Knowledge Map curriculum: modules, knowledge nodes, and
         *     progressive reveals. It is a discovery mechanic, not a scored assessment, so
         *     it is deliberately separate from mission issuance and scoring.
         */
        get: operations["get_learning_domain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/missions/issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issues a deterministic mission for a task. */
        post: operations["issue_mission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/missions/{mission_id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scores one attempt and returns immediate feedback. */
        post: operations["answer_mission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/missions/{mission_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Marks a mission completed. */
        post: operations["complete_mission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reconciles a batch of attempts, re-scoring each against canonical content. */
        post: operations["sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns a device's settled Bits balance. */
        get: operations["get_wallet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Answer primitives for one attempt. Exactly one field is set. */
        AnswerPayload: {
            /** @description Slot id to piece id assignments for configuration builder. */
            assignments?: {
                [key: string]: string;
            } | null;
            /** @description Ordered choice ids for troubleshooting or a scenario chain. */
            choice_path?: string[] | null;
            /** @description Directed `[from, to]` pairs for node connection. */
            edges?: string[][] | null;
            /** @description Selected evidence source ids for evidence selection. */
            evidence_ids?: string[] | null;
            /** @description Selected faulty element ids for spot the fault. */
            faulty_ids?: string[] | null;
            /** @description Item ids in submitted order for ordering. */
            ordered_ids?: string[] | null;
            /** @description Item id to category id placements for classification. */
            placements?: {
                [key: string]: string;
            } | null;
            /** @description Item id to position for two-dimensional placement. */
            positions?: {
                [key: string]: components["schemas"]["PlacementPoint"];
            } | null;
            reconstruction?: null | components["schemas"]["ReconstructionAnswerPayload"];
            /** @description Slot id to option id values for fill slots. */
            slot_values?: {
                [key: string]: string;
            } | null;
            /** @description Slot id to token id values for command assembly. */
            token_values?: {
                [key: string]: string;
            } | null;
        };
        /** @description Request to score one attempt. */
        AnswerRequest: {
            /** @description Answer primitives. */
            answer: components["schemas"]["AnswerPayload"];
            /**
             * Format: int32
             * @description 1-based attempt number.
             */
            attempt_number: number;
            /** @description Content version the client believes it is answering. */
            content_version: string;
            /**
             * Format: uuid
             * @description Client device identifier.
             */
            device_id: string;
            /**
             * Format: uuid
             * @description Stable event identifier for this attempt.
             */
            event_id: string;
            /**
             * Format: int32
             * @description Hints used before submitting.
             */
            hint_count: number;
            /**
             * Format: date-time
             * @description When the attempt occurred on the device.
             */
            occurred_at: string;
            /** @description Question being answered. */
            question_id: string;
            /**
             * Format: int32
             * @description Active response time in milliseconds.
             */
            response_ms: number;
        };
        /**
         * @description How an attempt measures knowledge.
         *
         *     The first four are the base evidence modes from `docs/06-learning-engine.md`.
         *     The remaining two are explicit Phase 1 subtypes used by tactile
         *     interactions; they are still treated as evidence modes, not proven
         *     independent latent abilities.
         * @enum {string}
         */
        AssessmentMode: "recognition" | "recall" | "application" | "structural_reconstruction" | "relationship_recall" | "procedural_recall";
        /** @description The canonical answer for a question. */
        CanonicalAnswer: {
            /** @description Item id to category id. */
            placements: {
                [key: string]: string;
            };
            /** @enum {string} */
            type: "classification";
        } | {
            /** @description Item ids in canonical order. */
            ordered_ids: string[];
            /** @enum {string} */
            type: "ordering";
        } | {
            /** @description Directed `[from, to]` pairs. */
            edges: string[][];
            /** @enum {string} */
            type: "node_connection";
        } | {
            /** @description Optional directed `[from, to]` piece-id pairs for `graph` layouts. */
            edges?: string[][];
            /** @description Slot id to piece id. */
            placements: {
                [key: string]: string;
            };
            /** @enum {string} */
            type: "reconstruction";
        } | {
            /** @description Relevant evidence ids. Every other candidate is a false positive. */
            relevant_ids: string[];
            /** @enum {string} */
            type: "evidence_selection";
        } | {
            /** @description Faulty element ids. */
            faulty_ids: string[];
            /** @enum {string} */
            type: "spot_the_fault";
        } | {
            /** @enum {string} */
            type: "fill_slots";
            /** @description Slot id to option id. */
            values: {
                [key: string]: string;
            };
        } | {
            /** @description Step id to the choice ids that are correct at that step. */
            correct_choice_ids: {
                [key: string]: string[];
            };
            /** @description The intended ordered choice ids from the start step. */
            expected_path: string[];
            /** @enum {string} */
            type: "troubleshooting";
        } | {
            /** @description Step id to the choice ids that are correct at that step. */
            correct_choice_ids: {
                [key: string]: string[];
            };
            /** @description The intended ordered choice ids from the start step. */
            expected_path: string[];
            /** @enum {string} */
            type: "scenario_choice_chain";
        } | {
            /** @description Slot id to piece id. */
            assignments: {
                [key: string]: string;
            };
            /** @enum {string} */
            type: "configuration_builder";
        } | {
            /** @description Item id to its canonical region. */
            regions: {
                [key: string]: components["schemas"]["PlacementRegion"];
            };
            /** @enum {string} */
            type: "two_dimensional_placement";
        } | {
            /** @enum {string} */
            type: "command_assembly";
            /** @description Slot id to token id. */
            values: {
                [key: string]: string;
            };
        };
        /** @description Response for the certification catalog. */
        CatalogResponse: {
            /** @description All known certifications. */
            certifications: components["schemas"]["CertificationDto"][];
        };
        /** @description A certification with its versioned blueprints. */
        CertificationDto: {
            /** @description Official exam code. */
            exam_code: string;
            /** @description Certification identifier. */
            id: string;
            /** @description Last blueprint review date. */
            last_reviewed: string;
            /** @description Full name. */
            name: string;
            /** @description Official blueprint source. */
            official_source_url: string;
            /** @description Vendor. */
            vendor: string;
            /** @description Known exam versions. */
            versions: components["schemas"]["CertificationVersionDto"][];
        };
        /** @description A versioned exam blueprint. */
        CertificationVersionDto: {
            /**
             * @description Learner-facing knowledge concepts referenced by this version.
             *
             *     Mission payloads carry only concept ids; the catalog supplies the names so
             *     summaries never have to render a raw identifier.
             */
            concepts: components["schemas"]["ConceptDto"][];
            /** @description Immutable content version. */
            content_version: string;
            /** @description Domains with authored tasks. */
            domains: components["schemas"]["DomainDto"][];
            /** @description Blueprint effective date. */
            effective_date: string;
            /** @description Official exam code. */
            exam_code: string;
            /** @description Version identifier. */
            id: string;
        };
        /** @description A selectable item or category. */
        Choice: {
            /** @description Stable identifier within the question. */
            id: string;
            /** @description Learner-facing label. */
            label: string;
        };
        /** @description Request to complete a mission. */
        CompleteMissionRequest: {
            /**
             * Format: uuid
             * @description Device that owns the mission.
             */
            device_id: string;
        };
        /** @description Completion result. */
        CompleteMissionResponse: {
            /**
             * Format: date-time
             * @description Completion time.
             */
            completed_at?: string | null;
            /**
             * Format: uuid
             * @description Mission identifier.
             */
            id: string;
            /** @description New status. */
            status: components["schemas"]["MissionStatus"];
        };
        /** @description A learner-facing knowledge concept. */
        ConceptDto: {
            /** @description Stable concept identifier, for example `aws.cloudformation.changesets`. */
            id: string;
            /** @description Short learner-facing name, for example `CloudFormation change sets`. */
            name: string;
        };
        /** @description A concept mapped to a question, with its share of the evidence. */
        ConceptWeight: {
            /** @description Concept identifier, for example `aws.cloudwatch.alarm`. */
            concept_id: string;
            /**
             * Format: double
             * @description Share of the question attributed to this concept, in `(0, 1]`.
             */
            weight: number;
        };
        /** @description A named role the learner assigns a component to. */
        ConfigSlot: {
            /** @description Stable identifier within the question. */
            id: string;
            /** @description Learner-facing label for the role, for example `IPv4 default route target`. */
            label: string;
        };
        /**
         * @description Database reachability.
         * @enum {string}
         */
        DatabaseStatus: "ok" | "unavailable";
        /** @description A content domain. */
        DomainDto: {
            /** @description Domain identifier. */
            id: string;
            /** @description Whether pre-quiz learning content exists for this domain. */
            learning_available: boolean;
            /** @description Domain name. */
            name: string;
            /** @description Tasks with authored content. */
            tasks: components["schemas"]["TaskDto"][];
            /**
             * Format: double
             * @description Share of scored content.
             */
            weight: number;
        };
        /** @description Structured error details. */
        ErrorBody: {
            /** @description Stable error code. */
            code: string;
            /** @description Safe, human-readable message. */
            message: string;
        };
        /** @description Envelope returned for every API error. */
        ErrorResponse: {
            /** @description Error payload. */
            error: components["schemas"]["ErrorBody"];
        };
        /** @description Feedback for one scored attempt. */
        FeedbackResponse: {
            /**
             * Format: int64
             * @description Bits the learner is expected to earn when this attempt is settled.
             *
             *     A preview only: the authoritative balance is settled during sync.
             */
            bits_preview: number;
            /** @description Canonical answer, revealed after scoring. */
            canonical_answer: components["schemas"]["CanonicalAnswer"];
            /** @description Concept mappings with weights. */
            concepts: components["schemas"]["ConceptWeight"][];
            /** @description Whether the attempt was fully correct. */
            correct: boolean;
            /** @description Structured error codes. */
            error_codes: string[];
            /**
             * Format: uuid
             * @description Event identifier echoed back.
             */
            event_id: string;
            /** @description Short explanation. */
            explanation: string;
            /** @description Question identifier. */
            question_id: string;
            /**
             * Format: double
             * @description Partial score in `[0, 1]`.
             */
            score: number;
        };
        /** @description A blank the learner must fill from a constrained option set. */
        FillSlot: {
            /** @description Stable identifier within the question. */
            id: string;
            /** @description Learner-facing label for the blank, for example `Destination`. */
            label: string;
        };
        /** @description A node that is already provided as part of the scaffold. */
        FixedNode: {
            /** @description Stable identifier within the question. */
            id: string;
            /** @description Learner-facing label. */
            label: string;
            /** @description Where the node is shown relative to the slots in `linear` layouts. */
            position: components["schemas"]["FixedNodePosition"];
            /**
             * Format: double
             * @description Authored horizontal position for `graph` layouts, in `0..=1`.
             */
            x?: number | null;
            /**
             * Format: double
             * @description Authored vertical position for `graph` layouts, in `0..=1`.
             */
            y?: number | null;
        };
        /**
         * @description Where a provided node sits relative to a reconstruction's slots.
         * @enum {string}
         */
        FixedNodePosition: "start" | "end";
        /**
         * @description Safe operational health payload. Never includes connection strings, hosts,
         *     versions of dependencies, or other internals.
         */
        HealthResponse: {
            /** @description Database status. */
            database: components["schemas"]["DatabaseStatus"];
            /** @description Service name. */
            service: string;
            /** @description Aggregate status. */
            status: components["schemas"]["HealthStatus"];
            /**
             * Format: date-time
             * @description Server time in UTC.
             */
            timestamp: string;
            /**
             * Format: int64
             * @description Seconds since process start.
             */
            uptime_seconds: number;
            /** @description Service version. */
            version: string;
        };
        /**
         * @description Overall service health.
         * @enum {string}
         */
        HealthStatus: "ok" | "degraded";
        /** @description Interaction definition shown to the learner. Contains no answer key. */
        Interaction: {
            /** @description Destination categories. */
            categories: components["schemas"]["Choice"][];
            /** @description Items to place. */
            items: components["schemas"]["Choice"][];
            /** @enum {string} */
            type: "classification";
        } | {
            /** @description Items to order. */
            items: components["schemas"]["Choice"][];
            /** @enum {string} */
            type: "ordering";
        } | {
            /** @description Nodes available to connect. */
            nodes: components["schemas"]["Node"][];
            /** @enum {string} */
            type: "node_connection";
        } | {
            /** @description Nodes already provided as context. Not part of the answer. */
            fixed_nodes: components["schemas"]["FixedNode"][];
            /** @description How the scaffold represents structure. */
            layout: components["schemas"]["ReconstructionLayout"];
            /** @description Candidate pieces, including plausible distractors. */
            pieces: components["schemas"]["Choice"][];
            /** @description Structural positions the learner fills. */
            slots: components["schemas"]["ReconstructionSlot"][];
            /** @enum {string} */
            type: "reconstruction";
        } | {
            /** @description Candidate telemetry, log, or evidence sources. */
            evidence: components["schemas"]["Choice"][];
            /** @enum {string} */
            type: "evidence_selection";
        } | {
            /** @description Structured elements (components, rules, rows) the learner inspects. */
            elements: components["schemas"]["Choice"][];
            /** @enum {string} */
            type: "spot_the_fault";
        } | {
            /** @description Values the learner may use. May contain distractors. */
            options: components["schemas"]["Choice"][];
            /** @description Blanks to fill, in presentation order. */
            slots: components["schemas"]["FillSlot"][];
            /** @enum {string} */
            type: "fill_slots";
        } | {
            /** @description Step the scenario starts at. */
            start_step_id: string;
            /** @description Authored decision steps. */
            steps: components["schemas"]["ScenarioStep"][];
            /** @enum {string} */
            type: "troubleshooting";
        } | {
            /** @description Step the scenario starts at. */
            start_step_id: string;
            /** @description Authored decision steps. */
            steps: components["schemas"]["ScenarioStep"][];
            /** @enum {string} */
            type: "scenario_choice_chain";
        } | {
            /** @description Components the learner may assign. May contain distractors. */
            pieces: components["schemas"]["Choice"][];
            /** @description Named roles that each expect one component. */
            slots: components["schemas"]["ConfigSlot"][];
            /** @enum {string} */
            type: "configuration_builder";
        } | {
            /** @description Items the learner positions. */
            items: components["schemas"]["Choice"][];
            /** @enum {string} */
            type: "two_dimensional_placement";
            /** @description Horizontal axis definition. */
            x_axis: components["schemas"]["PlacementAxis"];
            /** @description Vertical axis definition. */
            y_axis: components["schemas"]["PlacementAxis"];
        } | {
            /** @description Ordered parts of the statement. */
            slots: components["schemas"]["FillSlot"][];
            /** @description Tokens the learner may use. May contain distractors. */
            tokens: components["schemas"]["Choice"][];
            /** @enum {string} */
            type: "command_assembly";
        };
        /**
         * @description The tactile interaction family a question uses.
         * @enum {string}
         */
        InteractionType: "classification" | "ordering" | "node_connection" | "reconstruction" | "evidence_selection" | "spot_the_fault" | "fill_slots" | "troubleshooting" | "scenario_choice_chain" | "configuration_builder" | "two_dimensional_placement" | "command_assembly";
        /** @description Request to issue a mission for a quiz mode. */
        IssueMissionRequest: {
            /** @description Certification identifier. */
            certification_id: string;
            /** @description Certification version identifier. */
            certification_version: string;
            /**
             * Format: uuid
             * @description Client device identifier.
             */
            device_id: string;
            /** @description Domain to scope a domain quiz to. Ignored for other modes. */
            domain_id?: string | null;
            /** @description Quiz mode deciding how the server selects questions. */
            mode: components["schemas"]["QuizMode"];
            /** @description Task to scope a task practice to. Required for `task_practice`. */
            task_id?: string | null;
        };
        /** @description One knowledge card on the map. */
        KnowledgeNode: {
            /** @description Certification concepts this node teaches. The bridge to quiz evidence. */
            concept_ids: string[];
            /** @description Stable node identifier. */
            id: string;
            /** @description Authored position on the map in `0..=1` space. */
            map_position: components["schemas"]["MapPosition"];
            /** @description Nodes that must be unlocked before this node becomes ready. */
            prerequisite_node_ids?: string[];
            /** @description Progressive reveal prompts. All required prompts unlock the node. */
            prompts: components["schemas"]["KnowledgePrompt"][];
            /** @description Official references for this node. */
            source_refs?: components["schemas"]["SourceRef"][];
            /** @description Learner-facing node title. */
            title: string;
        };
        /** @description One progressive-reveal prompt on a knowledge card. */
        KnowledgePrompt: {
            /** @description Stable prompt identifier within the node. */
            id: string;
            /** @description Prompt kind, which selects the shared icon and styling vocabulary. */
            kind: components["schemas"]["PromptKind"];
            /** @description Learner-facing label, authored by the curriculum. */
            label: string;
            /** @description Blank text shown before the reveal. */
            placeholder: string;
            /** @description Whether revealing this prompt counts toward unlocking the node. */
            required?: boolean;
            /** @description The information revealed when the learner taps the blank. */
            reveal: components["schemas"]["LearningReveal"];
        };
        /** @description The vocabulary and rules shown to learners on the map. */
        LearningDesign: {
            /** @description Reminder that discovery is not mastery. */
            mastery_note: string;
            /** @description Label for discovery progress, for example `Discovery Progress`. */
            progress_label: string;
            /** @description Explanation of the unlock rule. */
            unlock_rule: string;
        };
        /** @description Domain identity within a certification blueprint. */
        LearningDomainMeta: {
            /** @description Domain identifier, for example `domain-1`. */
            id: string;
            /** @description Official domain name. */
            name: string;
            /**
             * Format: double
             * @description Share of scored content, in `(0, 1]`.
             */
            weight: number;
        };
        /**
         * @description Learner-facing learning content for one certification domain.
         *
         *     This is the discovery layer that sits before retrieval practice. Reveals are
         *     present because progressive disclosure is the mechanic, not a secret. Quiz
         *     canonical answers are never included.
         */
        LearningDomainResponse: {
            /** @description Certification identifier. */
            certification_id: string;
            /** @description Certification version identifier. */
            certification_version: string;
            /** @description Immutable learning content version. */
            content_version: string;
            /** @description Domain identity and weight. */
            domain: components["schemas"]["LearningDomainMeta"];
            /** @description Official exam guide revision. */
            exam_guide_revision?: string | null;
            /** @description Learner-facing vocabulary and unlock rules. */
            learning_design: components["schemas"]["LearningDesign"];
            /** @description Modules with their knowledge nodes. */
            modules: components["schemas"]["LearningModule"][];
            /** @description Learning schema version. */
            schema_version: string;
            /** @description Domain-level references. */
            source_refs: components["schemas"]["SourceRef"][];
        };
        /** @description A group of knowledge nodes unlocked along one path. */
        LearningModule: {
            /** @description Stable module identifier. */
            id: string;
            /** @description Knowledge nodes in presentation order. */
            nodes: components["schemas"]["KnowledgeNode"][];
            /**
             * Format: int64
             * @description Presentation order within the domain.
             */
            order: number;
            /** @description Modules that must be completed before this one becomes available. */
            prerequisite_module_ids?: string[];
            /** @description Exam skill ids this module teaches. */
            skill_ids?: string[];
            /** @description Exam task ids this module teaches. */
            task_ids?: string[];
            /** @description Learner-facing module title. */
            title: string;
        };
        /**
         * @description How a revealed prompt renders. Deliberately not a plain string: the
         *     curriculum distinguishes prose, sequences, comparisons, and keyword clues.
         */
        LearningReveal: {
            /** @description Revealed text. Keep it to one or two sentences. */
            text: string;
            /** @enum {string} */
            type: "text";
        } | {
            /** @description Ordered items. */
            items: string[];
            /** @enum {string} */
            type: "sequence";
        } | {
            /** @description Bullet items. */
            items: string[];
            /** @enum {string} */
            type: "bullets";
        } | {
            /** @description Clue items. */
            items: string[];
            /** @enum {string} */
            type: "keywords";
        } | {
            /** @description Comparison columns. */
            columns: components["schemas"]["RevealColumn"][];
            /** @enum {string} */
            type: "comparison";
        };
        /** @description Normalized position on the knowledge map. */
        MapPosition: {
            /**
             * Format: double
             * @description Horizontal position in `0..=1`.
             */
            x: number;
            /**
             * Format: double
             * @description Vertical position in `0..=1`.
             */
            y: number;
        };
        /** @description A server-issued mission with its questions. */
        MissionResponse: {
            /** @description Certification identifier. */
            certification_id: string;
            /** @description Certification version identifier. */
            certification_version: string;
            /** @description Immutable content version. */
            content_version: string;
            /**
             * Format: uuid
             * @description Device the mission belongs to.
             */
            device_id: string;
            /** @description Domain covered, for domain quizzes. */
            domain_id?: string | null;
            /**
             * Format: date-time
             * @description Expiry time.
             */
            expires_at: string;
            /**
             * Format: uuid
             * @description Mission identifier.
             */
            id: string;
            /**
             * Format: date-time
             * @description Issue time.
             */
            issued_at: string;
            /** @description Quiz mode. */
            mode: components["schemas"]["QuizMode"];
            /** @description Questions in presentation order. */
            questions: components["schemas"]["QuestionView"][];
            /** @description Task covered, for task practice. */
            task_id?: string | null;
        };
        /**
         * @description Lifecycle of a server-issued mission.
         * @enum {string}
         */
        MissionStatus: "issued" | "completed";
        /** @description A node in a connection graph. */
        Node: {
            /** @description Stable identifier within the question. */
            id: string;
            /** @description Learner-facing label. */
            label: string;
            /**
             * Format: double
             * @description Horizontal position in an abstract `0..=1` layout space.
             */
            x: number;
            /**
             * Format: double
             * @description Vertical position in an abstract `0..=1` layout space.
             */
            y: number;
        };
        /** @description One axis of a two-dimensional conceptual map. */
        PlacementAxis: {
            /** @description Label for the high end of the axis. */
            high_label: string;
            /** @description Stable identifier within the question. */
            id: string;
            /** @description Learner-facing axis name. */
            label: string;
            /** @description Label for the low end of the axis. */
            low_label: string;
        };
        /** @description A point submitted for a two-dimensional placement. */
        PlacementPoint: {
            /**
             * Format: double
             * @description Horizontal position in `0..=1`.
             */
            x: number;
            /**
             * Format: double
             * @description Vertical position in `0..=1`.
             */
            y: number;
        };
        /** @description A tolerant canonical region on a two-dimensional map. */
        PlacementRegion: {
            /** @description Inclusive `[min, max]` horizontal range in `0..=1`. */
            x: number[];
            /** @description Inclusive `[min, max]` vertical range in `0..=1`. */
            y: number[];
        };
        /**
         * @description The shared prompt vocabulary. Icons are selected by the UI from this kind,
         *     so content can change labels without the renderer special-casing nodes.
         * @enum {string}
         */
        PromptKind: "what" | "when" | "connects_to" | "not_this" | "exam_clue" | "mental_model" | "action" | "look_for";
        /** @description A question shown to the learner. Contains no answer key. */
        QuestionView: {
            /** @description Evidence mode. */
            assessment_mode: components["schemas"]["AssessmentMode"];
            /** @description Concept mappings. */
            concepts: components["schemas"]["ConceptWeight"][];
            /**
             * Format: double
             * @description Prior difficulty.
             */
            difficulty_prior: number;
            /** @description Owning domain. */
            domain_id: string;
            /** @description Optional hints. */
            hints: string[];
            /** @description Question identifier. */
            id: string;
            /** @description Interaction definition. */
            interaction: components["schemas"]["Interaction"];
            /** @description Interaction family. */
            interaction_type: components["schemas"]["InteractionType"];
            /** @description Learner-facing prompt. */
            prompt: string;
            /** @description Owning task. */
            task_id: string;
        };
        /**
         * @description The quiz mode a mission was issued for.
         *
         *     `task_practice` is kept for the demo/task flow and internal debugging; the
         *     three learner-facing modes are quick, domain, and full practice.
         * @enum {string}
         */
        QuizMode: "quick_adaptive" | "domain_quiz" | "full_practice" | "task_practice";
        /** @description Reconstruction answer primitives. */
        ReconstructionAnswerPayload: {
            /** @description Directed `[from, to]` relationships the learner drew. */
            edges?: string[][];
            /** @description Slot id to piece id placements. */
            placements: {
                [key: string]: string;
            };
        };
        /**
         * @description How a reconstruction scaffold represents structure.
         * @enum {string}
         */
        ReconstructionLayout: "linear" | "graph";
        /** @description A structural position the learner fills with a piece. */
        ReconstructionSlot: {
            /** @description Stable identifier within the question. */
            id: string;
            /**
             * Format: double
             * @description Authored horizontal position for `graph` layouts, in `0..=1`.
             */
            x?: number | null;
            /**
             * Format: double
             * @description Authored vertical position for `graph` layouts, in `0..=1`.
             */
            y?: number | null;
        };
        /** @description One titled column of a comparison reveal. */
        RevealColumn: {
            /** @description Column items. */
            items: string[];
            /** @description Column heading. */
            title: string;
        };
        /**
         * @description The operational stage a branching-scenario decision belongs to.
         *
         *     The stage is used only to attach a structured error code to a poor decision;
         *     it is not a measure of overall mastery.
         * @enum {string}
         */
        ScenarioStage: "diagnosis" | "action" | "remediation" | "verification";
        /** @description One authored decision point in a branching scenario. */
        ScenarioStep: {
            /** @description Choices available at this step. */
            choices: components["schemas"]["Choice"][];
            /** @description Stable identifier within the scenario. */
            id: string;
            /** @description Choice id to next step id. A choice with no entry ends the scenario. */
            next_step_by_choice: {
                [key: string]: string;
            };
            /** @description Learner-facing situation or question. */
            prompt: string;
            /** @description What kind of decision this step represents. */
            stage: components["schemas"]["ScenarioStage"];
        };
        /** @description A reference to the official source of a content unit. */
        SourceRef: {
            /** @description Display title. */
            title: string;
            /** @description URL. */
            url: string;
        };
        /** @description One attempt in a sync batch. */
        SyncEventRequest: {
            /** @description Answer primitives. */
            answer: components["schemas"]["AnswerPayload"];
            /**
             * Format: int32
             * @description 1-based attempt number.
             */
            attempt_number: number;
            /** @description Content version the answer was produced against. */
            content_version: string;
            /**
             * Format: uuid
             * @description Stable event identifier.
             */
            event_id: string;
            /**
             * Format: int32
             * @description Hints used.
             */
            hint_count: number;
            /**
             * Format: uuid
             * @description Mission the attempt belongs to.
             */
            mission_instance_id: string;
            /**
             * Format: date-time
             * @description When the attempt occurred.
             */
            occurred_at: string;
            /** @description Question answered. */
            question_id: string;
            /**
             * Format: int32
             * @description Active response time in milliseconds.
             */
            response_ms: number;
        };
        /** @description Result for one synced event. */
        SyncEventResult: {
            /** @description Whether the event is now accepted server-side. */
            accepted: boolean;
            /**
             * Format: int64
             * @description Bits settled for this event (0 when rejected or already settled).
             */
            bits_settled: number;
            /** @description Error code when not accepted. */
            error_code?: string | null;
            /**
             * Format: uuid
             * @description Event identifier.
             */
            event_id: string;
        };
        /** @description Request to sync a batch of evaluated attempts. */
        SyncRequest: {
            /**
             * Format: uuid
             * @description Client device identifier.
             */
            device_id: string;
            /** @description Attempts to reconcile. */
            events: components["schemas"]["SyncEventRequest"][];
        };
        /** @description Result of a sync batch. */
        SyncResponse: {
            /**
             * Format: int64
             * @description Authoritative settled Bits balance after this batch.
             */
            bits_balance: number;
            /** @description Per-event results. */
            results: components["schemas"]["SyncEventResult"][];
        };
        /** @description A task with a count of authored questions. */
        TaskDto: {
            /** @description Task identifier. */
            id: string;
            /** @description Task name. */
            name: string;
            /** @description Number of authored questions available. */
            question_count: number;
        };
        /** @description A device's settled Bits balance. */
        WalletResponse: {
            /**
             * Format: int64
             * @description Settled Bits balance.
             */
            bits_balance: number;
            /**
             * Format: uuid
             * @description Device the wallet belongs to.
             */
            device_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service and database are healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service is running but the database is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    openapi_json: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI 3 document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_certifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Certification catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogResponse"];
                };
            };
        };
    };
    get_learning_domain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Certification identifier, for example `aws-soa-c03`. */
                certification_id: string;
                /** @description Domain identifier, for example `domain-1`. */
                domain_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Domain learning content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningDomainResponse"];
                };
            };
            /** @description No learning content for this domain */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    issue_mission: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueMissionRequest"];
            };
        };
        responses: {
            /** @description Issued mission */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unknown certification or task */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    answer_mission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Mission identifier */
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description Scored attempt */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Invalid answer */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Mission belongs to another device */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unknown mission */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Mission completed or content version mismatch */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    complete_mission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Mission identifier */
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteMissionRequest"];
            };
        };
        responses: {
            /** @description Mission completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteMissionResponse"];
                };
            };
            /** @description Mission belongs to another device */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unknown mission */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    sync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRequest"];
            };
        };
        responses: {
            /** @description Per-event sync results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_wallet: {
        parameters: {
            query: {
                /** @description Client device identifier. */
                device_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settled Bits balance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletResponse"];
                };
            };
        };
    };
}
