/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness and dependency check.
         * @description Returns `200` when the database is reachable and `503` when it is not, so a
         *     load balancer can stop routing to an instance whose dependency is down.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serves the generated OpenAPI document.
         * @description The document is the source of truth for the TypeScript client. Regenerate it
         *     with `cargo run -p adaptive-learn-api --bin export-openapi` or the web
         *     `pnpm generate:api` script.
         */
        get: operations["openapi_json"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Database reachability.
         * @enum {string}
         */
        DatabaseStatus: "ok" | "unavailable";
        /** @description Structured error details. */
        ErrorBody: {
            /** @description Stable error code. */
            code: string;
            /** @description Safe, human-readable message. */
            message: string;
        };
        /** @description Envelope returned for every API error. */
        ErrorResponse: {
            /** @description Error payload. */
            error: components["schemas"]["ErrorBody"];
        };
        /**
         * @description Safe operational health payload. Never includes connection strings, hosts,
         *     versions of dependencies, or other internals.
         */
        HealthResponse: {
            /** @description Database status. */
            database: components["schemas"]["DatabaseStatus"];
            /** @description Service name. */
            service: string;
            /** @description Aggregate status. */
            status: components["schemas"]["HealthStatus"];
            /**
             * Format: date-time
             * @description Server time in UTC.
             */
            timestamp: string;
            /**
             * Format: int64
             * @description Seconds since process start.
             */
            uptime_seconds: number;
            /** @description Service version. */
            version: string;
        };
        /**
         * @description Overall service health.
         * @enum {string}
         */
        HealthStatus: "ok" | "degraded";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service and database are healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service is running but the database is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    openapi_json: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI 3 document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
